// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN_tZm1q1pbRTosbqk2rqnwUKOi5rVZPs',
    appId: '1:897650118984:web:66022674090fce452e637d',
    messagingSenderId: '897650118984',
    projectId: 'growhut-c6d37',
    authDomain: 'growhut-c6d37.firebaseapp.com',
    storageBucket: 'growhut-c6d37.appspot.com',
    measurementId: 'G-SXEE5LF3Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp0D5iwpBXC-8uejBqPtns_7hNNBOva-g',
    appId: '1:897650118984:android:5e0864e584612ebe2e637d',
    messagingSenderId: '897650118984',
    projectId: 'growhut-c6d37',
    storageBucket: 'growhut-c6d37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIbXdTKC7O2rTgIEyMY_Mns6MiH0bG0yY',
    appId: '1:897650118984:ios:d236ba5649554b652e637d',
    messagingSenderId: '897650118984',
    projectId: 'growhut-c6d37',
    storageBucket: 'growhut-c6d37.appspot.com',
    iosBundleId: 'com.example.taxiAttendenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIbXdTKC7O2rTgIEyMY_Mns6MiH0bG0yY',
    appId: '1:897650118984:ios:229a438fc6febfed2e637d',
    messagingSenderId: '897650118984',
    projectId: 'growhut-c6d37',
    storageBucket: 'growhut-c6d37.appspot.com',
    iosBundleId: 'com.example.taxiAttendenceApp.RunnerTests',
  );
}
